{
 "title": "Telegraf: system dashboard",
 "description": "Prometheus/victoriametrics dashboards for telegraf metrics",
 "tags": [
  "prometheus",
  "telegraf",
  "victoriametrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   { "name": "server", "label": "Server", "query": "label_values(host)" },
   { "name": "mountpoint", "label": "Mountpoint", "query": "label_values(path)" },
   { "name": "cpu", "label": "CPU", "query": "label_values(cpu)" },
   { "name": "disk", "label": "Disk", "query": "label_values(name)" },
   { "name": "netif", "label": "Network interface", "query": "label_values(interface)" }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "type": "field", "params": [ "uptime" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "system_uptime{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "type": "field", "params": [ "load5" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "system_load5{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "processes",
     "select": [
      [
       { "type": "field", "params": [ "zombies" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "processes_zombies{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "processes",
     "select": [
      [
       { "type": "field", "params": [ "total" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "processes_total{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "processes",
     "select": [
      [
       { "type": "field", "params": [ "total_threads" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "processes_total_threads{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "type": "field", "params": [ "usage_idle" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\",cpu = \"cpu-total\"}",
     "expr": "100-cpu_usage_idle{host =~ \"^$server$\",cpu = \"cpu-total\"}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "type": "field", "params": [ "used_percent" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "mem_used_percent{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "swap",
     "select": [
      [
       { "type": "field", "params": [ "used_percent" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "swap_used_percent{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "disk",
     "select": [
      [
       { "type": "field", "params": [ "used_percent" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\",path = \"/\"}",
     "expr": "disk_used_percent{host =~ \"^$server$\",path = \"/\"}"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "field", "params": [ "usage_iowait" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\",cpu = \"cpu-total\"}",
     "expr": "cpu_usage_iowait{host =~ \"^$server$\",cpu = \"cpu-total\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_user) as user from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_user" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "user",
     "expr": "median(cpu_usage_user{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: user"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_system) as system from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_system" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "system",
     "expr": "median(cpu_usage_system{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: system"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_softirq) as softirq from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_softirq" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "softirq",
     "expr": "median(cpu_usage_softirq{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: softirq"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_steal) as steal from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_steal" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "steal",
     "expr": "median(cpu_usage_steal{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: steal"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_nice) as nice from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_nice" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "nice",
     "expr": "median(cpu_usage_nice{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: nice"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_irq) as irq from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_irq" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "irq",
     "expr": "median(cpu_usage_irq{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: irq"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_iowait) as iowait from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_iowait" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "iowait",
     "expr": "median(cpu_usage_iowait{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: iowait"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_guest) as guest from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_guest" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "guest",
     "expr": "median(cpu_usage_guest{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: guest"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_guest_nice) as guest_nice from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_guest_nice" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}",
     "col": "guest_nice",
     "expr": "median(cpu_usage_guest_nice{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "legendFormat": "{{host}}: guest_nice"
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "system",
     "query": "select mean(load1) as short from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "load1" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "short",
     "expr": "median(system_load1{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: short"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "system",
     "query": "select mean(load5) as medium from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "load5" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "medium",
     "expr": "median(system_load5{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: medium"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "system",
     "query": "select mean(load15) as long from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "load15" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "long",
     "expr": "median(system_load15{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: long"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "processes",
     "query": "select mean(running) as running from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "running" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "running",
     "expr": "median(processes_running{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: running"
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "processes",
     "query": "select mean(blocked) as blocked from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "blocked" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "blocked",
     "expr": "median(processes_blocked{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: blocked"
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "processes",
     "query": "select mean(sleeping) as sleeping from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "sleeping" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "sleeping",
     "expr": "median(processes_sleeping{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: sleeping"
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "processes",
     "query": "select mean(stopped) as stopped from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "stopped" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "stopped",
     "expr": "median(processes_stopped{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: stopped"
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "processes",
     "query": "select mean(zombies) as zombies from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "zombies" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "zombies",
     "expr": "median(processes_zombies{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: zombies"
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "processes",
     "query": "select mean(paging) as paging from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "paging" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "paging",
     "expr": "median(processes_paging{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: paging"
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "processes",
     "query": "select mean(unknown) as unknown from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "unknown" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "unknown",
     "expr": "median(processes_unknown{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: unknown"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "mem",
     "query": "select mean(total) as total from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "total" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "total",
     "expr": "median(mem_total{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: total"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "mem",
     "query": "select mean(used) as used from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "used" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "used",
     "expr": "median(mem_used{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: used"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "mem",
     "query": "select mean(cached) as cached from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "cached" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "cached",
     "expr": "median(mem_cached{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: cached"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "mem",
     "query": "select mean(free) as free from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "free" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "free",
     "expr": "median(mem_free{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: free"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "mem",
     "query": "select mean(buffered) as buffered from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "buffered" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "buffered",
     "expr": "median(mem_buffered{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: buffered"
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "kernel",
     "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "context_switches" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "expr": "abs(ideriv(median(kernel_context_switches{host =~ \"$server$\"}) by (host)))",
     "legendFormat": "{{host}}: context_switches"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "kernel",
     "query": "SELECT non_negative_derivative(mean(processes_forked),1s) as forks FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "processes_forked" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "col": "forks",
     "expr": "abs(ideriv(median(kernel_processes_forked{host =~ \"^$server$\"}) by (host)))",
     "legendFormat": "{{host}}: forks"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "linux_sysctl_fs",
     "query": "SELECT mean(\"file-max\") as max FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "type": "mean", "params": [ "file-max" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "col": "max",
     "expr": "median(linux_sysctl_fs_file-max{host =~ \"^$server$\"}) by (host)",
     "legendFormat": "{{host}}: max"
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": " by (host)",
     "measurement": "linux_sysctl_fs",
     "query": "SELECT mean(\"file-nr\") as opened FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "type": "mean", "params": [ "file-nr" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "col": "opened",
     "expr": "median(linux_sysctl_fs_file-nr{host =~ \"^$server$\"}) by (host)",
     "legendFormat": "{{host}}: opened"
    }
   ]
  },
  { "title": "Interrupts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_irq",
     "groupBy": " by (irq,host)",
     "measurement": "interrupts",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "total" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(interrupts_total{host =~ \"^$server$\"}) by (irq,host)))",
     "legendFormat": "{{host}}: {{irq}}"
    }
   ]
  },
  { "title": "Per-cpu usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU usage for $cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "repeat": "cpu",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_user) as user from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_user" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "user",
     "expr": "median(cpu_usage_user{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu user"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_system) as system from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_system" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "system",
     "expr": "median(cpu_usage_system{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu system"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_softirq) as softirq from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_softirq" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "softirq",
     "expr": "median(cpu_usage_softirq{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu softirq"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_steal) as steal from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_steal" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "steal",
     "expr": "median(cpu_usage_steal{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu steal"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_nice) as nice from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_nice" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "nice",
     "expr": "median(cpu_usage_nice{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu nice"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_irq) as irq from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_irq" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "irq",
     "expr": "median(cpu_usage_irq{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu irq"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_iowait) as iowait from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_iowait" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "iowait",
     "expr": "median(cpu_usage_iowait{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu iowait"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_guest) as guest from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_guest" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "guest",
     "expr": "median(cpu_usage_guest{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu guest"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "cpu",
     "query": "select mean(usage_guest_nice) as guest_nice from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "mean", "params": [ "usage_guest_nice" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}",
     "col": "guest_nice",
     "expr": "median(cpu_usage_guest_nice{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "legendFormat": "{{host}}: $cpu guest_nice"
    }
   ]
  },
  { "title": "Conntrack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Netfilter conntrack usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$server: current",
     "measurement": "conntrack",
     "select": [
      [
       { "type": "mean", "params": [ "ip_conntrack_count" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "median(conntrack_ip_conntrack_count{host =~ \"^$server$\"})",
     "legendFormat": "$server: current"
    },
    {
     "alias": "$server: maximum",
     "measurement": "conntrack",
     "select": [
      [
       { "type": "mean", "params": [ "ip_conntrack_max" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "median(conntrack_ip_conntrack_max{host =~ \"^$server$\"})",
     "legendFormat": "$server: maximum"
    }
   ]
  },
  { "title": "Network stack (TCP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_close) as CLOSED from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_close" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "CLOSED",
     "expr": "median(netstat_tcp_close{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: CLOSED"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_close_wait) as CLOSE_WAIT from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_close_wait" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "CLOSE_WAIT",
     "expr": "median(netstat_tcp_close_wait{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: CLOSE_WAIT"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_closing) as CLOSING from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_closing" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "CLOSING",
     "expr": "median(netstat_tcp_closing{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: CLOSING"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_established) as ESTABLISHED from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_established" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "ESTABLISHED",
     "expr": "median(netstat_tcp_established{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: ESTABLISHED"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_fin_wait1) as FIN_WAIT1 from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_fin_wait1" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "FIN_WAIT1",
     "expr": "median(netstat_tcp_fin_wait1{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: FIN_WAIT1"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_fin_wait2) as FIN_WAIT2 from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_fin_wait2" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "FIN_WAIT2",
     "expr": "median(netstat_tcp_fin_wait2{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: FIN_WAIT2"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_last_ack) as LAST_ACK from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_last_ack" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "LAST_ACK",
     "expr": "median(netstat_tcp_last_ack{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: LAST_ACK"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_syn_recv) as SYN_RECV from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_syn_recv" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "SYN_RECV",
     "expr": "median(netstat_tcp_syn_recv{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: SYN_RECV"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_syn_sent) as SYN_SENT from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_syn_sent" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "SYN_SENT",
     "expr": "median(netstat_tcp_syn_sent{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: SYN_SENT"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "netstat",
     "query": "select mean(tcp_time_wait) as TIME_WAIT from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "tcp_time_wait" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "TIME_WAIT",
     "expr": "median(netstat_tcp_time_wait{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: TIME_WAIT"
    }
   ]
  },
  {
   "title": "TCP aborts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "on close",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtTCPAbortOnClose" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnClose{host =~ \"^$server$\"})))",
     "legendFormat": "on close"
    },
    {
     "alias": "on data",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtTCPAbortOnData" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnData{host =~ \"^$server$\"})))",
     "legendFormat": "on data"
    },
    {
     "alias": "timeout",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtTCPAbortOnTimeout" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnTimeout{host =~ \"^$server$\"})))",
     "legendFormat": "timeout"
    },
    {
     "alias": "failed",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtTCPAbortFailed" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortFailed{host =~ \"^$server$\"})))",
     "legendFormat": "failed"
    },
    {
     "alias": "linger",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtTCPAbortOnLinger" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnLinger{host =~ \"^$server$\"})))",
     "legendFormat": "linger"
    },
    {
     "alias": "memory",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtTCPAbortOnMemory" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnMemory{host =~ \"^$server$\"})))",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "TCP handshake issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "estabresets",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "tcp_estabresets" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(net_tcp_estabresets{host =~ \"^$server$\"})))",
     "legendFormat": "estabresets"
    },
    {
     "alias": "outrsts",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(tcp_outrsts), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "tcp_outrsts" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(net_tcp_outrsts{host =~ \"^$server$\"})))",
     "legendFormat": "outrsts"
    },
    {
     "alias": "activeopens",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(tcp_activeopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "tcp_activeopens" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(net_tcp_activeopens{host =~ \"^$server$\"})))",
     "legendFormat": "activeopens"
    },
    {
     "alias": "passiveopens",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(tcp_passiveopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "tcp_passiveopens" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(net_tcp_passiveopens{host =~ \"^$server$\"})))",
     "legendFormat": "passiveopens"
    }
   ]
  },
  {
   "title": "TCP SYN cookies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "failed",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtSyncookiesFailed" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_TcpExtSyncookiesFailed{host =~ \"^$server$\"})))",
     "legendFormat": "failed"
    },
    {
     "alias": "received",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtSyncookiesRecv" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_TcpExtSyncookiesRecv{host =~ \"^$server$\"})))",
     "legendFormat": "received"
    },
    {
     "alias": "sent",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "TcpExtSyncookiesSent" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_TcpExtSyncookiesSent{host =~ \"^$server$\"})))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "ICMP packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "in echos",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IcmpInEchos" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IcmpInEchos{host =~ \"^$server$\"})))",
     "legendFormat": "in echos"
    },
    {
     "alias": "out echos",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IcmpOutEchos" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IcmpOutEchos{host =~ \"^$server$\"})))",
     "legendFormat": "out echos"
    },
    {
     "alias": "in echo responses",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IcmpInEchoReps" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IcmpInEchoReps{host =~ \"^$server$\"})))",
     "legendFormat": "in echo responses"
    },
    {
     "alias": "out echo responses",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IcmpOutEchoReps" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IcmpOutEchoReps{host =~ \"^$server$\"})))",
     "legendFormat": "out echo responses"
    }
   ]
  },
  {
   "title": "ICMP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IcmpInErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IcmpInErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in errors"
    },
    {
     "alias": "out errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IcmpOutErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IcmpOutErrors{host =~ \"^$server$\"})))",
     "legendFormat": "out errors"
    },
    {
     "alias": "checksum errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IcmpInCsumErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IcmpInCsumErrors{host =~ \"^$server$\"})))",
     "legendFormat": "checksum errors"
    }
   ]
  },
  {
   "title": "IPv4 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in discards",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IpInDiscards" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IpInDiscards{host =~ \"^$server$\"})))",
     "legendFormat": "in discards"
    },
    {
     "alias": "out discards",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IpOutDiscards" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IpOutDiscards{host =~ \"^$server$\"})))",
     "legendFormat": "out discards"
    },
    {
     "alias": "in hdr errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IpInHdrErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IpInHdrErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in hdr errors"
    },
    {
     "alias": "in addr errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IpInAddrErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IpInAddrErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in addr errors"
    },
    {
     "alias": "out no routes",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IpOutNoRoutes" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IpOutNoRoutes{host =~ \"^$server$\"})))",
     "legendFormat": "out no routes"
    },
    {
     "alias": "in unknown protocol",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "IpInUnknownProtos" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_IpInUnknownProtos{host =~ \"^$server$\"})))",
     "legendFormat": "in unknown protocol"
    }
   ]
  },
  {
   "title": "IPv6 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in discards",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "Ip6InDiscards" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_Ip6InDiscards{host =~ \"^$server$\"})))",
     "legendFormat": "in discards"
    },
    {
     "alias": "out discards",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "Ip6OutDiscards" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_Ip6OutDiscards{host =~ \"^$server$\"})))",
     "legendFormat": "out discards"
    },
    {
     "alias": "in hdr errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "Ip6InHdrErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_Ip6InHdrErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in hdr errors"
    },
    {
     "alias": "in addr errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "Ip6InAddrErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_Ip6InAddrErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in addr errors"
    },
    {
     "alias": "out no routes",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "Ip6OutNoRoutes" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_Ip6OutNoRoutes{host =~ \"^$server$\"})))",
     "legendFormat": "out no routes"
    },
    {
     "alias": "in unknown protocol",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "Ip6InUnknownProtos" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_Ip6InUnknownProtos{host =~ \"^$server$\"})))",
     "legendFormat": "in unknown protocol"
    }
   ]
  },
  { "title": "Network stack (UDP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "UDP datagrams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(udp_indatagrams), 1s) as \"in datagrams\" FROM \"net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "udp_indatagrams" ] }
      ]
     ],
     "tags": "{host =~ \"$server\"}",
     "col": "in datagrams",
     "expr": "abs(ideriv(median(net_udp_indatagrams{host =~ \"$server\"}) by (host)))",
     "legendFormat": "{{host}}: in datagrams"
    },
    {
     "alias": "$tag_host: $col",
     "function": "derivative",
     "groupBy": " by (host)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(udp_outdatagrams), 1s) as \"out datagrams\" FROM \"net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "udp_outdatagrams" ] }
      ]
     ],
     "tags": "{host =~ \"$server\"}",
     "col": "out datagrams",
     "expr": "abs(ideriv(median(net_udp_outdatagrams{host =~ \"$server\"}) by (host)))",
     "legendFormat": "{{host}}: out datagrams"
    }
   ]
  },
  {
   "title": "UDP buffer errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Send buffer errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "UdpSndbufErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_UdpSndbufErrors{host =~ \"^$server$\"})))",
     "legendFormat": "Send buffer errors"
    },
    {
     "alias": "Receive buffer errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "UdpRcvbufErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_UdpRcvbufErrors{host =~ \"^$server$\"})))",
     "legendFormat": "Receive buffer errors"
    }
   ]
  },
  {
   "title": "UDP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "checksum errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "UdpInCsumErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_UdpInCsumErrors{host =~ \"^$server$\"})))",
     "legendFormat": "checksum errors"
    },
    {
     "alias": "in errors",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "UdpInErrors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_UdpInErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in errors"
    },
    {
     "alias": "no ports",
     "measurement": "nstat",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "UdpNoPorts" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(ideriv(median(nstat_UdpNoPorts{host =~ \"^$server$\"})))",
     "legendFormat": "no ports"
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "repeat": "netif"
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\"  FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "bytes_recv" ] }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}",
     "col": "in",
     "expr": "abs(ideriv(median(net_bytes_recv{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))*8",
     "legendFormat": "{{host}}: {{interface}}: in"
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "bytes_sent" ] }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}",
     "col": "out",
     "expr": "abs(ideriv(median(net_bytes_sent{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))*8",
     "legendFormat": "{{host}}: {{interface}}: out"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "packets_recv" ] }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}",
     "col": "in",
     "expr": "abs(ideriv(median(net_packets_recv{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "legendFormat": "{{host}}: {{interface}}: in"
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "packets_sent" ] }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}",
     "col": "out",
     "expr": "abs(ideriv(median(net_packets_sent{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "legendFormat": "{{host}}: {{interface}}: out"
    }
   ]
  },
  {
   "title": "Network drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "pps", "label": "Drops per second" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(drop_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "drop_in" ] }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}",
     "col": "in",
     "expr": "abs(ideriv(median(net_drop_in{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "legendFormat": "{{host}}: {{interface}}: in"
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(drop_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "drop_out" ] }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}",
     "col": "out",
     "expr": "abs(ideriv(median(net_drop_out{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "legendFormat": "{{host}}: {{interface}}: out"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(err_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "err_in" ] }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}",
     "col": "in",
     "expr": "abs(ideriv(median(net_err_in{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "legendFormat": "{{host}}: {{interface}}: in"
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(err_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "err_out" ] }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}",
     "col": "out",
     "expr": "abs(ideriv(median(net_err_out{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "legendFormat": "{{host}}: {{interface}}: out"
    }
   ]
  },
  { "title": "Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "swap",
     "query": "select non_negative_derivative(mean(in)) as in from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "in" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "in",
     "expr": "abs(idelta(median(swap_in{host =~ \"$server$\"}) by (host)))",
     "legendFormat": "{{host}}: in"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "swap",
     "query": "select non_negative_derivative(mean(out)) as out from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "out" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "out",
     "expr": "abs(idelta(median(swap_out{host =~ \"$server$\"}) by (host)))",
     "legendFormat": "{{host}}: out"
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "swap",
     "query": "select mean(used) as used from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "used" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "used",
     "expr": "median(swap_used{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: used"
    },
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": " by (host)",
     "measurement": "swap",
     "query": "select mean(total) as total from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "type": "mean", "params": [ "total" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\"}",
     "col": "total",
     "expr": "median(swap_total{host =~ \"$server$\"}) by (host)",
     "legendFormat": "{{host}}: total"
    }
   ]
  },
  { "title": "Disk IOPS for /dev/$disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 }, "repeat": "disk" },
  {
   "title": "Disk I/O requests for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": " by (host,name)",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "reads" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}",
     "col": "read",
     "expr": "abs(ideriv(median(diskio_reads{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "legendFormat": "{{host}}: {{name}}: read"
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": " by (host,name)",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "writes" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}",
     "col": "write",
     "expr": "abs(ideriv(median(diskio_writes{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "legendFormat": "{{host}}: {{name}}: write"
    }
   ]
  },
  {
   "title": "Disk I/O bytes for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 141 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": " by (host,name)",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "read_bytes" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}",
     "col": "read",
     "expr": "abs(ideriv(median(diskio_read_bytes{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "legendFormat": "{{host}}: {{name}}: read"
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": " by (host,name)",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "write_bytes" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}",
     "col": "write",
     "expr": "abs(ideriv(median(diskio_write_bytes{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "legendFormat": "{{host}}: {{name}}: write"
    }
   ]
  },
  {
   "title": "Disk I/O time for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 141 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": " by (host,name)",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "read_time" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}",
     "col": "read",
     "expr": "abs(ideriv(median(diskio_read_time{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "legendFormat": "{{host}}: {{name}}: read"
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": " by (host,name)",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "write_time" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}",
     "col": "write",
     "expr": "abs(ideriv(median(diskio_write_time{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "legendFormat": "{{host}}: {{name}}: write"
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 },
   "repeat": "mountpoint"
  },
  {
   "title": "Disk usage for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": " by (host,path)",
     "measurement": "disk",
     "query": "select mean(total) AS total from \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "type": "mean", "params": [ "total" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",path =~ \"^$mountpoint$\"}",
     "col": "total",
     "expr": "median(disk_total{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) by (host,path)",
     "legendFormat": "{{host}}: mountpoint {{path}} - total"
    },
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": " by (host,path)",
     "measurement": "disk",
     "query": "select mean(used) as used from \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "type": "mean", "params": [ "used" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",path =~ \"^$mountpoint$\"}",
     "col": "used",
     "expr": "median(disk_used{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) by (host,path)",
     "legendFormat": "{{host}}: mountpoint {{path}} - used"
    }
   ]
  },
  {
   "title": "Disk inodes for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": " by (host,path)",
     "measurement": "disk",
     "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "type": "mean", "params": [ "inodes_used" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",path =~ \"^$mountpoint$\"}",
     "col": "used",
     "expr": "median(disk_inodes_used{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) by (host,path)",
     "legendFormat": "{{host}}: mountpoint {{path}} - used"
    },
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": " by (host,path)",
     "measurement": "disk",
     "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "type": "mean(inodes_free) + mean", "params": [ "inodes_used" ] }
      ]
     ],
     "tags": "{host =~ \"$server$\",path =~ \"^$mountpoint$\"}",
     "col": "total",
     "expr": "median(disk_inodes_free{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) + median(disk_inodes_used{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) by (host,path)",
     "legendFormat": "{{host}}: mountpoint {{path}} - total"
    }
   ]
  },
  { "title": "Metrics velocity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "title": "Delivery time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Delivery time",
     "measurement": "internal_write",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "write_time_ns" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(internal_write_write_time_ns{host =~ \"^$server$\"})))",
     "legendFormat": "Delivery time"
    }
   ]
  },
  {
   "title": "Gather time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 157 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Gather time",
     "measurement": "internal_gather",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "gather_time_ns" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(internal_gather_gather_time_ns{host =~ \"^$server$\"})))",
     "legendFormat": "Gather time"
    }
   ]
  },
  {
   "title": "Written metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Metrics written",
     "measurement": "internal_agent",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "metrics_written" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(internal_agent_metrics_written{host =~ \"^$server$\"})))",
     "legendFormat": "Metrics written"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Gather errors",
     "measurement": "internal_agent",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "gather_errors" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(internal_agent_gather_errors{host =~ \"^$server$\"})))",
     "legendFormat": "Gather errors"
    },
    {
     "alias": "Dropped metrics",
     "measurement": "internal_agent",
     "select": [
      [
       { "type": "non_negative_derivative(mean", "params": [ "metrics_dropped" ] }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}",
     "expr": "abs(idelta(median(internal_agent_metrics_dropped{host =~ \"^$server$\"})))",
     "legendFormat": "Dropped metrics"
    }
   ]
  }
 ]
}